#!/bin/bash
mkdir -p mbuild
pushd mbuild >& /dev/null
#export CXX=/usr/bin/clang++-libc++
#export CC=/usr/bin/clang
cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
cmake --build .
popd >& /dev/null
